// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication.Models;

public partial class Alimento
{
    [Key]
    public int Id { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string Nombre { get; set; }

    [Column(TypeName = "money")]
    public decimal? Precio { get; set; }

    public int? Stock { get; set; }

    public int? StockMinimo { get; set; }

    public int? ProveedorID { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string url { get; set; }

    public int? Calorias { get; set; }

    [InverseProperty("Alimento")]
    public virtual ICollection<Dosis> Dosis { get; set; } = new List<Dosis>();

    [ForeignKey("ProveedorID")]
    [InverseProperty("Alimento")]
    public virtual Proveedores Proveedor { get; set; }
}