// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication.Models;

public partial class Alimentacion
{
    [Key]
    public int Id { get; set; }

    [StringLength(10)]
    public string Dieta { get; set; }
}