// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace WebApplication.Models;

public partial class Alimento
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public decimal? Precio { get; set; }

    public int? Stock { get; set; }

    public int? StockMinimo { get; set; }

    public int? ProveedorId { get; set; }

    public string Url { get; set; }

    public int? Calorias { get; set; }

    public virtual ICollection<Dosi> Dosis { get; set; } = new List<Dosi>();

    public virtual Proveedore Proveedor { get; set; }
}