// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication.Models;

public partial class Animal
{
    [Key]
    public int Id { get; set; }

    [StringLength(10)]
    public string Especie { get; set; }

    [Column("Nombre Popular")]
    [StringLength(10)]
    public string Nombre_Popular { get; set; }

    public int? EcosistemaID { get; set; }

    [Column("url imagen")]
    [StringLength(255)]
    public string url_imagen { get; set; }

    public int? JaulaId { get; set; }

    public int? AlimentacionID { get; set; }

    [InverseProperty("Animal")]
    public virtual ICollection<Dosis> Dosis { get; set; } = new List<Dosis>();

    [ForeignKey("JaulaId")]
    [InverseProperty("Animal")]
    public virtual Jaula Jaula { get; set; }
}