// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication.Models;

public partial class Animal
{
    public int Id { get; set; }

    public string Especie { get; set; }

    public string NombrePopular { get; set; }

    public int? EcosistemaId { get; set; }

    public string UrlImagen { get; set; }

    public int? JaulaId { get; set; }

    public virtual ICollection<Dosi> Dosis { get; set; } = new List<Dosi>();

    public virtual Jaula Jaula { get; set; }
}