// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication.Models;

public partial class CategoriasLaborale
{
    public int Id { get; set; }

    public string Descripcion { get; set; }

    public decimal? Sueldo { get; set; }

    public virtual ICollection<Empleado> Empleados { get; set; } = new List<Empleado>();
}