// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication.Models;

public partial class CategoriasLaborales
{
    [Key]
    public int Id { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Descripcion { get; set; }

    [Column(TypeName = "money")]
    public decimal? Sueldo { get; set; }

    [InverseProperty("Categorias")]
    public virtual ICollection<Empleados> Empleados { get; set; } = new List<Empleados>();
}