// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication.Models;

public partial class Dosi
{
    public int DosisId { get; set; }

    public int? AnimalId { get; set; }

    public int? AlimentoId { get; set; }

    public int? Cantidad { get; set; }

    public virtual Alimento Alimento { get; set; }

    public virtual Animal Animal { get; set; }
}