// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication.Models;

public partial class Dosis
{
    [Key]
    public int DosisID { get; set; }

    public int? AnimalID { get; set; }

    public int? AlimentoID { get; set; }

    public int? Cantidad { get; set; }

    [ForeignKey("AlimentoID")]
    [InverseProperty("Dosis")]
    public virtual Alimento Alimento { get; set; }

    [ForeignKey("AnimalID")]
    [InverseProperty("Dosis")]
    public virtual Animal Animal { get; set; }
}