// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication.Models;

public partial class Ecosistema
{
    public int Id { get; set; }

    public string Descripcion { get; set; }

    public string Url { get; set; }

    public virtual ICollection<Zona> Zonas { get; set; } = new List<Zona>();
}