// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication.Models;

public partial class Ecosistema
{
    [Key]
    public int Id { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string Descripcion { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string url { get; set; }

    [InverseProperty("Ecosistema")]
    public virtual ICollection<Zona> Zona { get; set; } = new List<Zona>();
}