// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication.Models;

public partial class Empleado
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string Apodo { get; set; }

    public string Telefono { get; set; }

    public string Cp { get; set; }

    public int? CategoriasId { get; set; }

    public int? JaulaId { get; set; }

    public virtual CategoriasLaborale Categorias { get; set; }

    public virtual Jaula Jaula { get; set; }
}