// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication.Models;

public partial class Empleados
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Nombre { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Apodo { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Telefono { get; set; }

    [StringLength(5)]
    [Unicode(false)]
    public string CP { get; set; }

    public int? CategoriasId { get; set; }

    public int? JaulaID { get; set; }

    [ForeignKey("CategoriasId")]
    [InverseProperty("Empleados")]
    public virtual CategoriasLaborales Categorias { get; set; }

    [ForeignKey("JaulaID")]
    [InverseProperty("Empleados")]
    public virtual Jaula Jaula { get; set; }
}