// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication.Models;

public partial class Jaula
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(5)]
    [Unicode(false)]
    public string Codigo { get; set; }

    public int ZonaId { get; set; }

    [InverseProperty("Jaula")]
    public virtual ICollection<Animal> Animal { get; set; } = new List<Animal>();

    [InverseProperty("Jaula")]
    public virtual ICollection<Empleados> Empleados { get; set; } = new List<Empleados>();

    [ForeignKey("ZonaId")]
    [InverseProperty("Jaula")]
    public virtual Zona Zona { get; set; }
}