// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WebApplication.Models;

public partial class LocalDBMSSQLLocalDBContext : DbContext
{
    public LocalDBMSSQLLocalDBContext(DbContextOptions<LocalDBMSSQLLocalDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Alimento> Alimentos { get; set; }

    public virtual DbSet<Animal> Animals { get; set; }

    public virtual DbSet<CategoriasLaborale> CategoriasLaborales { get; set; }

    public virtual DbSet<Dosi> Doses { get; set; }

    public virtual DbSet<Ecosistema> Ecosistemas { get; set; }

    public virtual DbSet<Empleado> Empleados { get; set; }

    public virtual DbSet<Jaula> Jaulas { get; set; }

    public virtual DbSet<Proveedore> Proveedores { get; set; }

    public virtual DbSet<Zona> Zonas { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Alimento>(entity =>
        {
            entity.ToTable("Alimento");

            entity.Property(e => e.Nombre)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.Precio).HasColumnType("money");
            entity.Property(e => e.ProveedorId).HasColumnName("ProveedorID");
            entity.Property(e => e.Url)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("url");

            entity.HasOne(d => d.Proveedor).WithMany(p => p.Alimentos)
                .HasForeignKey(d => d.ProveedorId)
                .HasConstraintName("FK_Alimento_Proveedores");
        });

        modelBuilder.Entity<Animal>(entity =>
        {
            entity.ToTable("Animal");

            entity.Property(e => e.EcosistemaId).HasColumnName("EcosistemaID");
            entity.Property(e => e.Especie)
                .HasMaxLength(10)
                .IsFixedLength();
            entity.Property(e => e.NombrePopular)
                .HasMaxLength(10)
                .IsFixedLength()
                .HasColumnName("Nombre Popular");
            entity.Property(e => e.UrlImagen)
                .HasMaxLength(255)
                .HasColumnName("url imagen");

            entity.HasOne(d => d.Jaula).WithMany(p => p.Animals)
                .HasForeignKey(d => d.JaulaId)
                .HasConstraintName("FK_Animal_Jaula");
        });

        modelBuilder.Entity<CategoriasLaborale>(entity =>
        {
            entity.Property(e => e.Descripcion)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Sueldo).HasColumnType("money");
        });

        modelBuilder.Entity<Dosi>(entity =>
        {
            entity.HasKey(e => e.DosisId);

            entity.ToTable("Dosis");

            entity.Property(e => e.DosisId).HasColumnName("DosisID");
            entity.Property(e => e.AlimentoId).HasColumnName("AlimentoID");
            entity.Property(e => e.AnimalId).HasColumnName("AnimalID");

            entity.HasOne(d => d.Alimento).WithMany(p => p.Dosis)
                .HasForeignKey(d => d.AlimentoId)
                .HasConstraintName("FK_Dosis_Alimento");

            entity.HasOne(d => d.Animal).WithMany(p => p.Dosis)
                .HasForeignKey(d => d.AnimalId)
                .HasConstraintName("FK_Dosis_Animal");
        });

        modelBuilder.Entity<Ecosistema>(entity =>
        {
            entity.ToTable("Ecosistema");

            entity.Property(e => e.Descripcion)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.Url)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("url");
        });

        modelBuilder.Entity<Empleado>(entity =>
        {
            entity.Property(e => e.Apodo)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Cp)
                .HasMaxLength(5)
                .IsUnicode(false)
                .HasColumnName("CP");
            entity.Property(e => e.JaulaId).HasColumnName("JaulaID");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Telefono)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.Categorias).WithMany(p => p.Empleados)
                .HasForeignKey(d => d.CategoriasId)
                .HasConstraintName("FK_Empleados_CategoriasLaborales");

            entity.HasOne(d => d.Jaula).WithMany(p => p.Empleados)
                .HasForeignKey(d => d.JaulaId)
                .HasConstraintName("FK_Empleados_Jaula");
        });

        modelBuilder.Entity<Jaula>(entity =>
        {
            entity.ToTable("Jaula");

            entity.Property(e => e.Codigo)
                .IsRequired()
                .HasMaxLength(5)
                .IsUnicode(false)
                .IsFixedLength();

            entity.HasOne(d => d.Zona).WithMany(p => p.Jaulas)
                .HasForeignKey(d => d.ZonaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Jaula_Zona");
        });

        modelBuilder.Entity<Proveedore>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Direccion).IsUnicode(false);
            entity.Property(e => e.Nombre)
                .HasMaxLength(250)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Zona>(entity =>
        {
            entity.ToTable("Zona");

            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Ecosistema).WithMany(p => p.Zonas)
                .HasForeignKey(d => d.EcosistemaId)
                .HasConstraintName("FK_Zona_Ecosistema");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}