// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WebApplication.Models;

public partial class LocalDBMSSQLLocalDBContext : DbContext
{
    public LocalDBMSSQLLocalDBContext(DbContextOptions<LocalDBMSSQLLocalDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Alimentacion> Alimentacion { get; set; }

    public virtual DbSet<Alimento> Alimento { get; set; }

    public virtual DbSet<Animal> Animal { get; set; }

    public virtual DbSet<CategoriasLaborales> CategoriasLaborales { get; set; }

    public virtual DbSet<Dosis> Dosis { get; set; }

    public virtual DbSet<Ecosistema> Ecosistema { get; set; }

    public virtual DbSet<Empleados> Empleados { get; set; }

    public virtual DbSet<Jaula> Jaula { get; set; }

    public virtual DbSet<Proveedores> Proveedores { get; set; }

    public virtual DbSet<Zona> Zona { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Alimentacion>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Alimenta__3214EC07FFC54BA2");

            entity.Property(e => e.Dieta).IsFixedLength();
        });

        modelBuilder.Entity<Alimento>(entity =>
        {
            entity.HasOne(d => d.Proveedor).WithMany(p => p.Alimento).HasConstraintName("FK_Alimento_Proveedores");
        });

        modelBuilder.Entity<Animal>(entity =>
        {
            entity.Property(e => e.Especie).IsFixedLength();
            entity.Property(e => e.Nombre_Popular).IsFixedLength();

            entity.HasOne(d => d.Jaula).WithMany(p => p.Animal).HasConstraintName("FK_Animal_Jaula");
        });

        modelBuilder.Entity<Dosis>(entity =>
        {
            entity.HasOne(d => d.Alimento).WithMany(p => p.Dosis).HasConstraintName("FK_Dosis_Alimento");

            entity.HasOne(d => d.Animal).WithMany(p => p.Dosis).HasConstraintName("FK_Dosis_Animal");
        });

        modelBuilder.Entity<Empleados>(entity =>
        {
            entity.HasOne(d => d.Categorias).WithMany(p => p.Empleados).HasConstraintName("FK_Empleados_CategoriasLaborales");

            entity.HasOne(d => d.Jaula).WithMany(p => p.Empleados).HasConstraintName("FK_Empleados_Jaula");
        });

        modelBuilder.Entity<Jaula>(entity =>
        {
            entity.Property(e => e.Codigo).IsFixedLength();

            entity.HasOne(d => d.Zona).WithMany(p => p.Jaula)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Jaula_Zona");
        });

        modelBuilder.Entity<Proveedores>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<Zona>(entity =>
        {
            entity.HasOne(d => d.Ecosistema).WithMany(p => p.Zona).HasConstraintName("FK_Zona_Ecosistema");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}