// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication.Models;

public partial class Proveedore
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string Direccion { get; set; }

    public virtual ICollection<Alimento> Alimentos { get; set; } = new List<Alimento>();
}