// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication.Models;

public partial class Proveedores
{
    [Key]
    public int Id { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string Nombre { get; set; }

    [Unicode(false)]
    public string Direccion { get; set; }

    [InverseProperty("Proveedor")]
    public virtual ICollection<Alimento> Alimento { get; set; } = new List<Alimento>();
}