// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication.Models;

public partial class Zona
{
    public int ZonaId { get; set; }

    public string Descripcion { get; set; }

    public int? EcosistemaId { get; set; }

    public virtual Ecosistema Ecosistema { get; set; }

    public virtual ICollection<Jaula> Jaulas { get; set; } = new List<Jaula>();
}