// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication.Models;

public partial class Zona
{
    [Key]
    public int ZonaId { get; set; }

    [Required]
    [StringLength(50)]
    public string Descripcion { get; set; }

    public int? EcosistemaId { get; set; }

    [ForeignKey("EcosistemaId")]
    [InverseProperty("Zona")]
    public virtual Ecosistema Ecosistema { get; set; }

    [InverseProperty("Zona")]
    public virtual ICollection<Jaula> Jaula { get; set; } = new List<Jaula>();
}